### ISSUE TITLE
Add stream schema conversion

### ISSUE THREAD

**Issue by Romkisel** [epam/TimebaseCryptoConnectors#7]
Update stream schema if it does not match the one required by the specific connector

E.g.: you will get an error if the table does not contain the type:

```
java.lang.IllegalArgumentException: Message type [class com.epam.deltix.timebase.messages.service.SecurityFeedStatusMessage] is not allowed. Expected: [class com.epam.deltix.timebase.messages.universal.PackageHeader]
	at com.epam.deltix.qsrv.hf.pub.codec.RecordTypeMap.getCode(RecordTypeMap.java:84) ~[timebase-pub-6.0.21.jar:6.0.21]
	at com.epam.deltix.qsrv.hf.tickdb.pub.SimpleBoundEncoder.encode(SimpleBoundEncoder.java:69) ~[timebase-api-6.0.21.jar:6.0.21]
	at com.epam.deltix.qsrv.hf.tickdb.pub.SimpleBoundEncoder.encode(SimpleBoundEncoder.java:33) ~[timebase-api-6.0.21.jar:6.0.21]
	at com.epam.deltix.qsrv.hf.tickdb.comm.client.TickLoaderClient.send(TickLoaderClient.java:378) ~[timebase-client-6.0.21.jar:6.0.21]
	at com.epam.deltix.qsrv.hf.tickdb.comm.client.TickLoaderClient.send(TickLoaderClient.java:50) ~[timebase-client-6.0.21.jar:6.0.21]
	at com.epam.deltix.data.connectors.commons.TbMessageOutputFactory$2.send(TbMessageOutputFactory.java:90) ~[main/:na]
	at com.epam.deltix.data.connectors.commons.SymbolMapper$1.send(SymbolMapper.java:83) ~[main/:na]
	at com.epam.deltix.data.connectors.commons.MdProcessor.close(MdProcessor.java:133) ~[main/:na]
	at com.epam.deltix.data.connectors.commons.MdSingleWsFeed.onClose(MdSingleWsFeed.java:119) ~[main/:na]
	at com.epam.deltix.data.connectors.commons.SingleWsFeed.lambda$doClose$5(SingleWsFeed.java:274) ~[main/:na]
```

**Comment by Romkisel** [comment]
fixed in 0a01d85616f55d684f522504d9e122448ca98e85
